name: Fetch Stations List Content and Commit

on:
  schedule:
    # Run every hour (adjust cron as needed, e.g., '0 * * * *')
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows manual triggering from the GitHub Actions tab

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      # Grant write permission to the workflow's GITHUB_TOKEN
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch content from URL and save to file
      run: curl -o Data/stations.json "https://stcorpgeneral001.blob.core.windows.net/json-site-locator/sitelocator_PROD.json?sp=r&st=2026-01-08T17:37:58Z&se=2028-01-09T01:52:58Z&spr=https&sv=2024-11-04&sr=b&sig=%2BfQoOBdETdGsRGdPRfQ1hgBz59%2FjVwstwDqZnWRKLPQ%3D" # Replace with your URL and desired filename

    - name: Commit files if changed
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: "Automated data update from external URL"
        add: 'Data/stations.json' # The file you created in the previous step
      env:
        # Use the built-in GITHUB_TOKEN with the necessary permissions
        GITHUB_TOKEN: ${{ secrets.UPDATE_STATIONS }}

